name: Nightly checks
run-name: ${{ github.actor }} running nightly checks

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  composer-install-args: "--no-progress --no-interaction --prefer-dist --no-scripts --ignore-platform-reqs"

jobs:
  composer:
    name: "ğŸ“¦ Composer"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
    
    steps:
      - uses: actions/checkout@v4
        name: ğŸ›’ Checkout

      - name: ğŸ” Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: composer.json

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-versions }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-composer-

      - uses: php-actions/composer@v6
        name: ğŸ— PHP ${{ matrix.php-versions }} and Composer install
        with:
          args: ${{ env.composer-install-args }}
          php_version: ${{ matrix.php-versions }}
      - name: Validate Composer
        run: composer validate --strict
      - name: Security Check
        run: composer audit
  
  check:
    needs: composer
    name: "ğŸ›¡ï¸ Check"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
    
    steps:
      - uses: actions/checkout@v4
        name: ğŸ›’ Checkout
          
      - name: ğŸ” Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: composer.json

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-versions }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-composer-

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: "ğŸª PhpStan"
        id: phpstan
        run: composer phpstan
          
      - name: "ğŸ“ Code style"
        id: phpcs
        if: success() || steps.phpstan.outcome == 'failure'
        run: composer phpcs
          
      - name: "ğŸ§¹Rector"
        id: rector
        if: success() || steps.phpstan.outcome == 'failure' || steps.phpcs.outcome == 'failure'
        run: composer rector
